### ISSUE TITLE
unable to access home page 

### ISSUE THREAD

**Issue by SpeedyAstro** [patryk47853/MyLibrary-System#1]
hey buddy, i cloned your project to learn and contribute .
there is problem with sql file 
1. there is two tables with name books
2. i don;t know why sql file not working, spring keep throwing error "user_id" do not have default value. 

so i just created schema and let spring boot create all tables 
now i am trying to login with registered credential , i keep redirected to error page instead home.

**Comment by patryk47853** [comment]
Hello! 

thank you for contacting me. I will look around what's going on during this week and will let you know if the problem is solved.

**Comment by patryk47853** [comment]
Hello there again!

SQL script has been updated and it seems to work fine now.
<img width="400" alt="mysql" src="https://github.com/patryk47853/MyLibrary-System/assets/109095669/e96f2869-fb89-4a45-82f5-b96c2d0a13bb">

I think the main issue was about connecting to the database. Please visit "application.properties" file and update those fields:
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD

to your actual MySQL Workbench data. It worked for me.
I will also make sure to make those update to README file in 24 hours.

If you have more questions, please feel free to ask. However, please keep in mind that this project is currently in beta mode - I mean that there are some functionalities that still need to be implemented (and also HTML/CSS must be changed). By now, you should be able to create user account and library card, manage users and library cards as admin, and as librarian, you should be able to browse books via Google Books API (please remember to paste your API key to "application.properties" file!)

Have a nice day! :)

**Comment by patryk47853** [comment]
That's right, because the functionality is not coded yet. By now you can browse books as Admin in Dashboard -> Search Books.

**Comment by patryk47853** [comment]
I see you have updated your comment.

You can update manually your SQL table. For example, if you want to set user with ID 1 as an admin, try something like this:
```
UPDATE users_roles SET role_id = (SELECT id FROM roles WHERE name = 'ADMIN') WHERE user_id = 1;
```

However, I see that I have forgotten to change authentication system in the code, so the librarian's dashboard is not working properly by now. I will post an update tomorrow.

**Comment by patryk47853** [comment]
Code has been updated.
